### ISSUE TITLE
Configure the list of domains to not track

### ISSUE THREAD

**Issue by SergeyKanzhelev** [census-instrumentation/opencensus-csharp#107]
Eliminate this hardcode in auto-collector:

https://github.com/census-instrumentation/opencensus-csharp/blob/a502d139ebb694a3ba804548f53c2ba67083d4f0/src/OpenCensus.Collector.Dependencies/Implementation/HttpHandlerDiagnosticListener.cs#L53-L57

I suggest as an initial implementation just have a custom sampler that will work per-request object before the main sampler like suggested here: https://github.com/rakyll/opencensus-specs/blob/7ae3810847d951ae79d0576afc3fd2cf0e020862/trace/HTTP.md#sampling

**Comment by sandeshp** [comment]
Planning notes:

* DependenciesCollector, created early in the lifecycle, already takes in an …Options, which is currently a blank class.
* Add a callback Func to the ..Options so that the collector calls that upon each request.
* The callback function can return a different ISampler which would be used on the call.
* Then, we implement a DomainExcluderCallback which returns an ISampler implementation (exists - SampleNone) for calls from certain domains.

* Write a UT based on  public async Task HttpDepenenciesCollectorInjectsHeadersAsync() in https://github.com/census-instrumentation/opencensus-csharp/blob/develop/test/OpenCensus.Collector.Dependencies.Tests/BasicTests.cs

**Comment by SergeyKanzhelev** [comment]
Addressed via https://github.com/census-instrumentation/opencensus-csharp/pull/109
