### ISSUE TITLE
Zipkin exporter not working towards /v2 jaeger collector endpoint

### ISSUE THREAD

**Issue by ekarlso** [census-instrumentation/opencensus-csharp#133]
Start Jaeger
```
docker run -d --name jaeger   -e COLLECTOR_ZIPKIN_HTTP_PORT=9411   -p 5775:5775/udp   -p 6831:6831/udp   -p 6832:6832/udp   -p 5778:5778   -p 16686:16686   -p 14268:14268   -p 9411:9411   jaegertracing/all-in-one:1.11```

Run the example zipkin or anything alike and Jaeger will give http 400 back. I got this via Wireshark when using the example TestZipkin.cs

**Comment by ekarlso** [comment]
With zipkin's docker image it seems you get 404 also.

**Comment by rstraszewski** [comment]
I've also been trying this today, and had similar problem. I received 400. The problem is with ipv6 - zipkin exporter is trying to send spans with ipv6 with [scope ID](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses)  (part with percent in the end) and Jaeger is rejecting this with error:
`Unable to process request body: wrong ipv6`

**Comment by SergeyKanzhelev** [comment]
moved to OpenTelemetry
